project:
  type: website
  output-dir: "."
  
website:
  title: "GRUPO F"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: info.qmd
        text: Informe
      - href: analize.qmd
        text: Analisis
    tools:
      - icon: twitter
        href: https://github.com/Gomezt13/semillas_u2.git
      - icon: github
        href: https://github.com/Gomezt13/semillas_u2.git
  page-footer:
    right: "Built with [Quarto](https://quarto.org/)"
    left: "&copy; Copyright 2024, Programación y Análisis de Datos"

format:
  html:
    theme: cerulean
    toc: true
bibliography: ref.bib
csl: apa.csl # (Opcional: Para definir el estilo de citación)
editor: source