project:
  type: website

website:
  title: "GRUPO F"
  navbar:
    left:
      - text: "Inicio"
        href: index.qmd
      - text: "Sobre Nosotros"
        href: about.qmd
      - text: "Contacto"
        href: contacto.qmd
format:
  html:
    theme: cosmo
    toc: true
